const athletesList = [
  { name: 'Giannis Antetokounmpo' },
  { name: 'Ja Morant' },
  { name: 'Jayson Tatum' },
  { name: 'Kevin Durant' },
  { name: 'Kobe Bryant' },
  { name: 'LeBron James' },
  { name: 'Luka Dončić' },
  { name: 'Paul George' },
  { name: 'Russell Westbrook' },
  { name: 'Zion Williamson' },
  { name: 'Ada Hegerberg' },
  { name: 'Alex Morgan' },
  { name: 'Amandine Henry' },
  { name: 'Cristiano Ronaldo' },
  { name: 'Harry Kane' },
  { name: 'Kylian Mbappé' },
  { name: 'Lieke Martens' },
  { name: 'Marcus Rashford' },
  { name: 'Megan Rapinoe' },
  { name: 'Sam Kerr' },
  { name: "A'ja Wilson" },
  { name: 'Sabrina Ionescu' },
  { name: 'Mat Fraser' },
];

export default athletesList;
